# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaterRobot.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(897, 801)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_top = QtWidgets.QWidget(Form)
        self.widget_top.setStyleSheet("")
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_cam1 = QtWidgets.QLabel(self.widget_top)
        self.label_cam1.setStyleSheet("")
        self.label_cam1.setObjectName("label_cam1")
        self.horizontalLayout.addWidget(self.label_cam1)
        self.gridLayout.addWidget(self.widget_top, 0, 0, 1, 3)
        self.widget_right = QtWidgets.QWidget(Form)
        self.widget_right.setStyleSheet("")
        self.widget_right.setObjectName("widget_right")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_right)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView_waterdepth = PlotWidget(self.widget_right)
        self.graphicsView_waterdepth.setObjectName("graphicsView_waterdepth")
        self.verticalLayout.addWidget(self.graphicsView_waterdepth)
        self.label_deepth = QtWidgets.QLabel(self.widget_right)
        self.label_deepth.setObjectName("label_deepth")
        self.verticalLayout.addWidget(self.label_deepth)
        self.graphicsView_turbidity = PlotWidget(self.widget_right)
        self.graphicsView_turbidity.setObjectName("graphicsView_turbidity")
        self.verticalLayout.addWidget(self.graphicsView_turbidity)
        self.label_turbidity = QtWidgets.QLabel(self.widget_right)
        self.label_turbidity.setObjectName("label_turbidity")
        self.verticalLayout.addWidget(self.label_turbidity)
        self.graphicsView_ph = PlotWidget(self.widget_right)
        self.graphicsView_ph.setObjectName("graphicsView_ph")
        self.verticalLayout.addWidget(self.graphicsView_ph)
        self.label_ph = QtWidgets.QLabel(self.widget_right)
        self.label_ph.setObjectName("label_ph")
        self.verticalLayout.addWidget(self.label_ph)
        self.gridLayout.addWidget(self.widget_right, 1, 1, 1, 2)
        self.widget_left = QtWidgets.QWidget(Form)
        self.widget_left.setStyleSheet("")
        self.widget_left.setObjectName("widget_left")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_left)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_cam = QtWidgets.QHBoxLayout()
        self.horizontalLayout_cam.setContentsMargins(7, 7, 7, 7)
        self.horizontalLayout_cam.setObjectName("horizontalLayout_cam")
        self.btn_cma1 = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cma1.sizePolicy().hasHeightForWidth())
        self.btn_cma1.setSizePolicy(sizePolicy)
        self.btn_cma1.setMinimumSize(QtCore.QSize(150, 60))
        self.btn_cma1.setMaximumSize(QtCore.QSize(400, 200))
        self.btn_cma1.setObjectName("btn_cma1")
        self.horizontalLayout_cam.addWidget(self.btn_cma1)
        self.btn_light = QtWidgets.QPushButton(self.widget_left)
        self.btn_light.setMinimumSize(QtCore.QSize(150, 100))
        self.btn_light.setMaximumSize(QtCore.QSize(400, 200))
        self.btn_light.setObjectName("btn_light")
        self.horizontalLayout_cam.addWidget(self.btn_light)
        self.btn_sensor = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sensor.sizePolicy().hasHeightForWidth())
        self.btn_sensor.setSizePolicy(sizePolicy)
        self.btn_sensor.setMinimumSize(QtCore.QSize(150, 70))
        self.btn_sensor.setMaximumSize(QtCore.QSize(400, 200))
        self.btn_sensor.setObjectName("btn_sensor")
        self.horizontalLayout_cam.addWidget(self.btn_sensor)
        self.gridLayout_3.addLayout(self.horizontalLayout_cam, 1, 0, 1, 1)
        self.gridLayout_opration = QtWidgets.QGridLayout()
        self.gridLayout_opration.setContentsMargins(7, 7, 7, 7)
        self.gridLayout_opration.setObjectName("gridLayout_opration")
        self.btn_font = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_font.sizePolicy().hasHeightForWidth())
        self.btn_font.setSizePolicy(sizePolicy)
        self.btn_font.setMinimumSize(QtCore.QSize(90, 90))
        self.btn_font.setObjectName("btn_font")
        self.gridLayout_opration.addWidget(self.btn_font, 0, 1, 1, 1)
        self.btn_left = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_left.sizePolicy().hasHeightForWidth())
        self.btn_left.setSizePolicy(sizePolicy)
        self.btn_left.setMinimumSize(QtCore.QSize(90, 90))
        self.btn_left.setObjectName("btn_left")
        self.gridLayout_opration.addWidget(self.btn_left, 1, 0, 1, 1)
        self.btn_back = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back.sizePolicy().hasHeightForWidth())
        self.btn_back.setSizePolicy(sizePolicy)
        self.btn_back.setMinimumSize(QtCore.QSize(90, 90))
        self.btn_back.setObjectName("btn_back")
        self.gridLayout_opration.addWidget(self.btn_back, 1, 1, 1, 1)
        self.btn_right = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_right.sizePolicy().hasHeightForWidth())
        self.btn_right.setSizePolicy(sizePolicy)
        self.btn_right.setMinimumSize(QtCore.QSize(90, 90))
        self.btn_right.setObjectName("btn_right")
        self.gridLayout_opration.addWidget(self.btn_right, 1, 2, 1, 1)
        self.btn_float = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_float.sizePolicy().hasHeightForWidth())
        self.btn_float.setSizePolicy(sizePolicy)
        self.btn_float.setMinimumSize(QtCore.QSize(90, 0))
        self.btn_float.setObjectName("btn_float")
        self.gridLayout_opration.addWidget(self.btn_float, 0, 0, 1, 1)
        self.btn_dive = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_dive.sizePolicy().hasHeightForWidth())
        self.btn_dive.setSizePolicy(sizePolicy)
        self.btn_dive.setObjectName("btn_dive")
        self.gridLayout_opration.addWidget(self.btn_dive, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_opration, 2, 0, 1, 1)
        self.verticalLayout_login = QtWidgets.QVBoxLayout()
        self.verticalLayout_login.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_login.setObjectName("verticalLayout_login")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_ip = QtWidgets.QLabel(self.widget_left)
        self.label_ip.setObjectName("label_ip")
        self.horizontalLayout_3.addWidget(self.label_ip)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.widget_left)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.horizontalLayout_3.addWidget(self.lineEdit_ip)
        self.verticalLayout_login.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_pwd = QtWidgets.QLabel(self.widget_left)
        self.label_pwd.setObjectName("label_pwd")
        self.horizontalLayout_4.addWidget(self.label_pwd)
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.widget_left)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.horizontalLayout_4.addWidget(self.lineEdit_pwd)
        self.verticalLayout_login.addLayout(self.horizontalLayout_4)
        self.btn_connectToPi = QtWidgets.QPushButton(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_connectToPi.sizePolicy().hasHeightForWidth())
        self.btn_connectToPi.setSizePolicy(sizePolicy)
        self.btn_connectToPi.setMinimumSize(QtCore.QSize(200, 50))
        self.btn_connectToPi.setMaximumSize(QtCore.QSize(16777215, 200))
        self.btn_connectToPi.setObjectName("btn_connectToPi")
        self.verticalLayout_login.addWidget(self.btn_connectToPi)
        self.gridLayout_3.addLayout(self.verticalLayout_login, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_left, 1, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout.setRowStretch(0, 3)
        self.gridLayout.setRowStretch(1, 5)

        self.retranslateUi(Form)
        self.btn_font.clicked.connect(Form.font)
        self.btn_left.clicked.connect(Form.left)
        self.btn_back.clicked.connect(Form.back)
        self.btn_right.clicked.connect(Form.right)
        self.btn_dive.clicked.connect(Form.dive)
        self.btn_float.clicked.connect(Form.float)
        self.btn_cma1.clicked.connect(Form.font_cam)
        self.btn_light.clicked.connect(Form.open_light)
        self.btn_connectToPi.clicked.connect(Form.link_to_pi)
        self.btn_sensor.clicked.connect(Form.open_sensor)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_cam1.setText(_translate("Form", "前摄"))
        self.label_deepth.setText(_translate("Form", "水深传感器"))
        self.label_turbidity.setText(_translate("Form", "浊度传感器"))
        self.label_ph.setText(_translate("Form", "ph值"))
        self.btn_cma1.setText(_translate("Form", "打开前摄"))
        self.btn_light.setText(_translate("Form", "打开灯光"))
        self.btn_sensor.setText(_translate("Form", "打开传感器"))
        self.btn_font.setText(_translate("Form", "前"))
        self.btn_left.setText(_translate("Form", "左"))
        self.btn_back.setText(_translate("Form", "后"))
        self.btn_right.setText(_translate("Form", "右"))
        self.btn_float.setText(_translate("Form", "上浮"))
        self.btn_dive.setText(_translate("Form", "下潜"))
        self.label_ip.setText(_translate("Form", "ip : "))
        self.label_pwd.setText(_translate("Form", "端口:"))
        self.btn_connectToPi.setText(_translate("Form", "连接到树莓派"))


from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
